#!/bin/bash

# Find local IP (First non-loopback IPv4)
IP=$(hostname -I | awk '{print $1}')

if [ -z "$IP" ]; then
    echo "Could not detect IP. Defaulting to localhost."
    IP="localhost"
fi

echo "Detected IP: $IP"

CONFIG_FILE="../frontend/shared/config.js"

# Update config.js
cat > $CONFIG_FILE <<EOF
/**
 * Kisan AI Frontend Configuration
 * 
 * Auto-generated by update_config_ip.sh
 */

window.FARMX_CONFIG = {
    // Backend server URL (Local Network)
    API_URL: "http://${IP}:8000",

    // Optional: Enable debug logging
    DEBUG: true
};

// Log configuration on load
if (window.FARMX_CONFIG.DEBUG) {
    console.log("Kisan AI Config loaded:", window.FARMX_CONFIG);
}
EOF

echo "frontend/shared/config.js updated with IP: $IP"
echo "You can now rebuild the APK."
